name: Chocolatine
on:
  pull_request:
    branches-ignore:
      - ga-ignore-**
  push:
    branches-ignore:
      - ga-ignore-**
env:
  MIRROR_URL:
    "git@github.com:EpitechPromo2026/B-CPE-110-REN-1-1-pushswap-mael1.becel.git"
  EXECUTABLES:
    "a.out"
jobs:
  check_repository_cleanliness:
    name: Cleaning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: FIND=$(find . -name "#*#" -o -name "*~" -o -iname "*pain_au_chocolat*" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -wholename "*/tmp/*"); if [[ $FIND != "" ]]; then for element in $FIND; do echo "::error file=$element,line=1,title=Unwanted file detected::$element"; done; exit 1; fi

  check_program_compilation:
    name: Compiling
    needs: check_repository_cleanliness
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make
      - run: make clean
      - run: IFS=','; read -a array <<< "${{ env.EXECUTABLES }}"; for element in "${array[@]}"; do if [ -z $(ls | grep -w $element$) ]; then exit 1; fi; done

  run_tests:
    name: Tests
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make tests_run

  push_to_mirror:
    name: Mirorring
    needs: run_tests
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}