##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## makefile
##

all:
			make -C antman/
			make -C giantman

debug:
			make -C antman debug
			make -C giantman debug
clean:
			make -C antman clean
			make -C giantman clean

fclean:
			make -C antman fclean
			make -C giantman fclean

re:			fclean all
