make re
echo "========================================="
echo "Test 01  :  ./rush1-1 4 4 | ./rush3"
echo ""
echo "Basic test"
echo ""
echo "Have :"
./rush1-1 4 4 | ./rush3
echo ""
echo "Expected :"
echo "[rush1-1] 4 4"
echo ""
echo "========================================="
echo "Test 02  :  ./rush1-3 1 4 | ./rush3"
echo ""
echo "Square with  multiple correspondance"
echo ""
echo "Have :"
./rush1-2 3 4 | ./rush3
echo ""
echo "Expected :"
echo "[rush1-2] 3 4"
echo ""
echo "========================================="
echo "Test 03  :  ./rush1-3 0 4 | ./rush3"
echo ""
echo "Square of size 0"
echo ""
echo "Have :"
./rush1-3 0 4 | ./rush3
echo ""
echo "Expected :"
echo "Invalid size"
echo ""
echo "========================================="
echo "Test 04  :  echo 'T' | ./rush3"
echo ""
echo "Inexistant square"
echo ""
echo "Have :"
echo "T" | ./rush3
echo ""
echo "Expected :"
echo "none"
echo ""
echo "========================================="
echo "Test 04  :  ./rush1-4 -5 -3 | ./rush3"
echo ""
echo "Negative numbers"
echo ""
echo "Have :"
./rush1-4 -5 -3 | ./rush3
echo ""
echo "Expected :"
echo "Invalid size"
echo ""
echo "========================================="
echo "Test 05  :  ./rush1-5 999 999 | ./rush3"
echo ""
echo "Big numbers"
echo ""
echo "Have :"
./rush1-5 999 999 | ./rush3
echo ""
echo "Expected :"
echo "[rush1-5] 999 999"
echo ""
echo ""

